<a href="https://www.kaggle.com/code/chowdhurysalwa/mlb-2-1-assignment?scriptVersionId=346968691" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [79]:
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/zubairdhuddi/tips-dataset/tips.csv


# import libraries

In [80]:
import numpy as np
import pandas as pd

In [81]:
tips = pd.read_csv('/kaggle/input/datasets/zubairdhuddi/tips-dataset/tips.csv')

In [82]:
tips.head()

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4


# create np-array

# 1. create 1D, 2D, 3D and 4D array using np.array()

In [83]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [84]:
a = np.array([[1,2,3],[1,4,5]])
a

array([[1, 2, 3],
       [1, 4, 5]])

In [85]:
 np.array([[[1,2],[3,5]],[[4,6],[7,8]]])

array([[[1, 2],
        [3, 5]],

       [[4, 6],
        [7, 8]]])

In [86]:
c= np.array([[[[1,2],[5,6]],[[5,6],[7,8]]],[[[7,8],[9,10]],[[2,5],[4,1]]]])
c

array([[[[ 1,  2],
         [ 5,  6]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 7,  8],
         [ 9, 10]],

        [[ 2,  5],
         [ 4,  1]]]])

# create 1D, 2D, 3D and 4D array using arange() and reshape()

In [87]:
a = np.arange(5).reshape(5)
a

array([0, 1, 2, 3, 4])

In [88]:
b= np.arange(0,12).reshape(4,3)
print(b)
c= np.arange(12).reshape(3,2,2)
c

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [89]:
d = np.arange(16).reshape(2,2,2,2)
d

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

# create array using ones and zeros

In [90]:
a = np.ones((2,2,3))
print(a)
b= np.zeros((2,2))
print("Zeros:\n",b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
Zeros:
 [[0. 0.]
 [0. 0.]]


# using random

In [91]:
 a = np.random.random((3,3))
a

array([[0.84873092, 0.59437312, 0.33256978],
       [0.61359645, 0.0028708 , 0.93241152],
       [0.1706368 , 0.90608572, 0.30539909]])

In [92]:
np.round(np.random.random((3,5))*200)

array([[111.,  93., 121.,  85.,  40.],
       [182.,  35.,  66., 143., 130.],
       [ 18.,  73.,  83.,  70., 155.]])

# using linspace

In [93]:
np.linspace(20,50,30,dtype=int)

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 50])

# create 1D array of tip from tips dataframe

In [94]:
tips['tip'].to_numpy()

array([ 1.01,  1.66,  3.5 ,  3.31,  3.61,  4.71,  2.  ,  3.12,  1.96,
        3.23,  1.71,  5.  ,  1.57,  3.  ,  3.02,  3.92,  1.67,  3.71,
        3.5 ,  3.35,  4.08,  2.75,  2.23,  7.58,  3.18,  2.34,  2.  ,
        2.  ,  4.3 ,  3.  ,  1.45,  2.5 ,  3.  ,  2.45,  3.27,  3.6 ,
        2.  ,  3.07,  2.31,  5.  ,  2.24,  2.54,  3.06,  1.32,  5.6 ,
        3.  ,  5.  ,  6.  ,  2.05,  3.  ,  2.5 ,  2.6 ,  5.2 ,  1.56,
        4.34,  3.51,  3.  ,  1.5 ,  1.76,  6.73,  3.21,  2.  ,  1.98,
        3.76,  2.64,  3.15,  2.47,  1.  ,  2.01,  2.09,  1.97,  3.  ,
        3.14,  5.  ,  2.2 ,  1.25,  3.08,  4.  ,  3.  ,  2.71,  3.  ,
        3.4 ,  1.83,  5.  ,  2.03,  5.17,  2.  ,  4.  ,  5.85,  3.  ,
        3.  ,  3.5 ,  1.  ,  4.3 ,  3.25,  4.73,  4.  ,  1.5 ,  3.  ,
        1.5 ,  2.5 ,  3.  ,  2.5 ,  3.48,  4.08,  1.64,  4.06,  4.29,
        3.76,  4.  ,  3.  ,  1.  ,  4.  ,  2.55,  4.  ,  3.5 ,  5.07,
        1.5 ,  1.8 ,  2.92,  2.31,  1.68,  2.5 ,  2.  ,  2.52,  4.2 ,
        1.48,  2.  ,

# create 2D array of tip and total_bill form tips dataframe

In [95]:
a = tips[['tip','total_bill']].to_numpy()
a

array([[ 1.01, 16.99],
       [ 1.66, 10.34],
       [ 3.5 , 21.01],
       [ 3.31, 23.68],
       [ 3.61, 24.59],
       [ 4.71, 25.29],
       [ 2.  ,  8.77],
       [ 3.12, 26.88],
       [ 1.96, 15.04],
       [ 3.23, 14.78],
       [ 1.71, 10.27],
       [ 5.  , 35.26],
       [ 1.57, 15.42],
       [ 3.  , 18.43],
       [ 3.02, 14.83],
       [ 3.92, 21.58],
       [ 1.67, 10.33],
       [ 3.71, 16.29],
       [ 3.5 , 16.97],
       [ 3.35, 20.65],
       [ 4.08, 17.92],
       [ 2.75, 20.29],
       [ 2.23, 15.77],
       [ 7.58, 39.42],
       [ 3.18, 19.82],
       [ 2.34, 17.81],
       [ 2.  , 13.37],
       [ 2.  , 12.69],
       [ 4.3 , 21.7 ],
       [ 3.  , 19.65],
       [ 1.45,  9.55],
       [ 2.5 , 18.35],
       [ 3.  , 15.06],
       [ 2.45, 20.69],
       [ 3.27, 17.78],
       [ 3.6 , 24.06],
       [ 2.  , 16.31],
       [ 3.07, 16.93],
       [ 2.31, 18.69],
       [ 5.  , 31.27],
       [ 2.24, 16.04],
       [ 2.54, 17.46],
       [ 3.06, 13.94],
       [ 1.

# practice atleast 2 example for each using ndim, shape, size and itemsize

In [96]:
x=np.arange(9)
y = np.arange(12).reshape(3,4)
z = np.arange(27).reshape(3,3,3)
print("Dimention:\n",x.ndim,y.ndim,z.ndim)
print("Shape:\n",x.shape,y.shape,z.shape)
print("Size:\n",np.size(x),np.size(y),np.size(z))
print("Memory Size:\n",x.itemsize)


Dimention:
 1 2 3
Shape:
 (9,) (3, 4) (3, 3, 3)
Size:
 9 12 27
Memory Size:
 8


# change data type and memory size of any np-array using astype()

In [97]:
y = y.astype(np.float32)
print("Data Type:",y.dtype)
print("Itemsize:",y.itemsize)


Data Type: float32
Itemsize: 4


# create 2 same dimensional array and do scalar and vector operations

In [98]:
a = np.array([[1,2],[3,4]])
b=np.array([[3,4],[5,6]])
print("Scaler:\n",a*2)
print("Vector:\n",a+b)

Scaler:
 [[2 4]
 [6 8]]
Vector:
 [[ 4  6]
 [ 8 10]]


# find minimun and maximum tip

In [99]:
a

array([[1, 2],
       [3, 4]])

In [100]:
np.min(a,axis=0)

array([1, 2])

In [101]:
np.max(a,axis=1)

array([2, 4])

# find average total_bill and average tip

In [102]:
a = tips['tip']
b = tips['total_bill']


In [103]:
print("Mean:",np.mean(b)," ",np.mean(a))

Mean: 19.78594262295082   2.99827868852459


# find median total_bill

In [104]:
print("Median: ",np.median(b)," ",np.median(a))

Median:  17.795   2.9


# find standard deviasion and variance of tip

In [105]:
print("Standard Deviation:",np.std(b)," ",np.std(a))

Standard Deviation: 8.88415057777113   1.3807999538298958


In [106]:
print("Variance:",np.var(b)," ",np.var(a))

Variance: 78.92813148851113   1.9066085124966428


# find log values of tip

In [109]:
np.log(tips['tip'])

0      0.009950
1      0.506818
2      1.252763
3      1.196948
4      1.283708
         ...   
239    1.778336
240    0.693147
241    0.693147
242    0.559616
243    1.098612
Name: tip, Length: 244, dtype: float64

# apply round, floor and ceil operation on tip array

In [112]:
np.round(tips['tip'])

0      1.0
1      2.0
2      4.0
3      3.0
4      4.0
      ... 
239    6.0
240    2.0
241    2.0
242    2.0
243    3.0
Name: tip, Length: 244, dtype: float64

In [116]:
print("ceil:",np.ceil(tips['tip']))
print("Floor:",np.floor(tips['tip']))

ceil: 0      2.0
1      2.0
2      4.0
3      4.0
4      4.0
      ... 
239    6.0
240    2.0
241    2.0
242    2.0
243    3.0
Name: tip, Length: 244, dtype: float64
Floor: 0      1.0
1      1.0
2      3.0
3      3.0
4      3.0
      ... 
239    5.0
240    2.0
241    2.0
242    1.0
243    3.0
Name: tip, Length: 244, dtype: float64


# use 1D, 2D and 3D np-array, and apply indexing and slicing atleast 5 example for each (take example as your wish)

In [117]:
a = np.arange(10)
b = np.arange(12).reshape(3,4)
c = np.arange(27).reshape(3,3,3)
a,b,c

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],
 
        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],
 
        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]]))

In [121]:
a[4:9],b[1:,2:4],c[2,0:,1:]

(array([4, 5, 6, 7, 8]),
 array([[ 6,  7],
        [10, 11]]),
 array([[19, 20],
        [22, 23],
        [25, 26]]))

In [127]:
b[1:3],c[1,0:4,1:4]

(array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[10, 11],
        [13, 14],
        [16, 17]]))

# stacking and spliting

In [137]:
d = np.arange(27).reshape(3,9)
e = np.arange(28,55).reshape(3,9)
d,e

(array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23, 24, 25, 26]]),
 array([[28, 29, 30, 31, 32, 33, 34, 35, 36],
        [37, 38, 39, 40, 41, 42, 43, 44, 45],
        [46, 47, 48, 49, 50, 51, 52, 53, 54]]))

# use hstack() and vstack()

In [138]:
np.hstack((d,e)) , np.vstack((e,d))

(array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8, 28, 29, 30, 31, 32, 33, 34,
         35, 36],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 37, 38, 39, 40, 41, 42, 43,
         44, 45],
        [18, 19, 20, 21, 22, 23, 24, 25, 26, 46, 47, 48, 49, 50, 51, 52,
         53, 54]]),
 array([[28, 29, 30, 31, 32, 33, 34, 35, 36],
        [37, 38, 39, 40, 41, 42, 43, 44, 45],
        [46, 47, 48, 49, 50, 51, 52, 53, 54],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23, 24, 25, 26]]))

# use hsplit() and vsplit()

In [148]:
np.hsplit(d,3),np.vsplit(e,1)

([array([[ 0,  1,  2],
         [ 9, 10, 11],
         [18, 19, 20]]),
  array([[ 3,  4,  5],
         [12, 13, 14],
         [21, 22, 23]]),
  array([[ 6,  7,  8],
         [15, 16, 17],
         [24, 25, 26]])],
 [array([[28, 29, 30, 31, 32, 33, 34, 35, 36],
         [37, 38, 39, 40, 41, 42, 43, 44, 45],
         [46, 47, 48, 49, 50, 51, 52, 53, 54]])])